In [6]:
import numpy as np
x=np.random.randn(3,4,2)
print(x.shape)
s = 1
for i in x.shape:
    s *= i
print(int(s/x.shape[0]))

(3, 4, 2)
8


In [11]:
x=np.array([[-1, 1],[1,-2]])
out = np.zeros(x.shape)
print(out)
y=np.maximum(0, x)
print(y)

[[0. 0.]
 [0. 0.]]
[[0 1]
 [1 0]]


In [15]:
a = 'w'
a = 'w' + str(1)
print(a)

w1


In [16]:
list(range(10,0,-1))

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [17]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
import numpy as np
x = np.random.rand(2,3)
w = np.ones([2, 3], dtype=np.float32)
print(x)
p=0.3
print(y>=p)
y = (x>=p)/(1-p)
print(y)
print(w * y)

[[0.32340955 0.47800509 0.92933119]
 [0.56544229 0.05157258 0.43024634]]
[[False False  True]
 [False  True  True]]
[[1.42857143 1.42857143 1.42857143]
 [1.42857143 0.         1.42857143]]
[[1.42857143 1.42857143 1.42857143]
 [1.42857143 0.         1.42857143]]
